; This file was auto-generated by drush make
core = 7.x

api = 2
projects[] = drupal

; Modules
projects[] = ctools
projects[] = colorbox
projects[] = colors
projects[] = devel
projects[] = fullcalendar
projects[] = masquerade
projects[] = pathauto
projects[] = token
projects[] = views
projects[] = date

;Libraries
libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "http://jacklmoore.com/colorbox/colorbox.zip"
libraries[fullcalendar][download][type] = "get"
libraries[fullcalendar][download][url] = "http://arshaw.com/fullcalendar/downloads/fullcalendar-1.5.3.zip"
libraries[fullcalendar][download][subtree] = "fullcalendar"



